---
name: cmpsc-100-spring-2019-lab4
break: true
indent: 4
---

src/main:
    java:
        labfour/MusicGenerator.java:
            --single 8 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 5
            --fragment "new Date()" --count 1
            --fragment "String" --count 5
            --fragment "Random" --count 3
            --fragment "Player" --count 2
            --fragment ".play" --count 3
            --fragment "Pattern" --count 4
            --fragment "File(" --count 2
            --fragment "nextInt(" --count 2
            --fragment "if (" --count 2
            --fragment "else if" --count 1

writing/reflection.md:
    --paragraphs 3 --exact
    --words 150
--commits 6

--command "gradle -q --console plain run" --executes
